version: '3.1'

services:
  d4chat-app:
    image: d4-chat_0.1.0 # set your built image name
    container_name: d4chat-app
    restart: always
    environment:
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/d4-chat
    depends_on:
      - d4chat-postgres
  d4chat-postgres:
    image: postgres:14
    container_name: d4chat-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT_DERIVE}:${DB_PORT}"
    volumes:
      - d4chat-postgres:/var/lib/postgresql/data

volumes:
  d4chat-postgres:
    driver: local
